name = "standpoint"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-05-06"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "standpoint-db"
database_id = "fd850c4d-228e-4b0e-b0d1-d8591ed634d6"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDO"]
