INSERT OR IGNORE INTO standpoint_spectrum_cards (id, left_label, right_label) VALUES
	('harmless-dangerous', 'harmless', 'dangerous'),
	('normal-cursed', 'normal', 'cursed'),
	('overrated-underrated', 'overrated', 'underrated'),
	('ethical-unethical', 'ethical', 'unethical'),
	('private-thought-public-take', 'private thought', 'public take'),
	('npc-behaviour-main-character-behaviour', 'NPC behaviour', 'main character behaviour'),
	('cold-take-hot-take', 'cold take', 'hot take'),
	('reasonable-unhinged', 'reasonable', 'unhinged'),
	('minor-inconvenience-life-ruining', 'minor inconvenience', 'life-ruining'),
	('based-cringe', 'based', 'cringe'),
	('temporary-permanent', 'temporary', 'permanent'),
	('art-content', 'art', 'content'),
	('necessary-optional', 'necessary', 'optional'),
	('boring-interesting', 'boring', 'interesting'),
	('overpriced-worth-it', 'overpriced', 'worth it'),
	('specific-vague', 'specific', 'vague'),
	('local-opinion-global-truth', 'local opinion', 'global truth'),
	('comfort-zone-growth-zone', 'comfort zone', 'growth zone'),
	('play-it-safe-go-for-it', 'play it safe', 'go for it'),
	('follow-the-rules-break-the-rules', 'follow the rules', 'break the rules');
